name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      ## FIXME: Temporary workaround once Go 1.16 releases
      #run: make deps
      run: |
        go build -v -mod=vendor ./...
        go get github.com/cosmtrek/air@v1.15.1

    - name: Build
      run: make build

    - name: Test
      run: |
        make test
        make install
        make uninstall
